### ISSUE TITLE
subfolder?

### ISSUE THREAD

**Issue by persianphilosopher** [sebastianks/volcano#1]
Thanks for this neat project. I am enjoying it so far and I like how you have built it to be flexible.

One issue I have - and I hope I am not getting it wrong - is about the pages' structure.
 If I place an md file in the "pages" folder, it renders it perfectly. But if I place anything in a subfolder, I can't get it to work. 

In other words, I can do:
`https://example.com/firstpost`
but this
`https://example.com/subfolder/firstpost`
does not work.

Is that on purpose? Am I doing something wrong? Thanks a lot

**Comment by sebastianks** [comment]
Hi @persianphilosopher 

Thanks for trying out Volcano, and for your kind words 😄 

The goal for Volcano is to be a CMS for websites - not blogs. Therefore it's not possible to nest inside `/site/pages`. I believe pages on a website shouldn't be nested, like you do on a blog with categories etc..

**But** if you're up for it, it's possible to make Volcano bloggy by creating a plugin that would work as a router, so that you can request: `https://example.com/my-page/another-page`. There's a function called `url_params()` that holds all the routes in the URL like so:

```
// url: example.com/my-page/another-page/third-page
$routes = url_params();
$routes[0] = 'my-page';
$routes[1] = 'another-page';
$routes[2] = 'third-page';
```

With this you could get a file inside `/site/pages/` by using `parse_markdown()` like so: (I just updated `parse_markdown()` to be able to do this. You have to pull latest from master branch.)

_`parse_markdown`_ takes 2 arguments: $filename and $nested_path. It's root is: `/site/pages/` so it's possible to do something like this:
```
$folder = '/' . $routes[0];
$filename = $routes[1];
parse_markdown($filename, $folder);
```
With this it's trying to get a file called `another-page.md` inside `/site/pages/my-page`.

I hope this is what you're looking for - let me know if I can help you with anything else. (Actually - while writing this I realised it could be useful for users if they could nest their content in folders, so this might be integrated by default in a future release of Volcano.)

_Also - I am working on an admin panel, which is basically a plugin. There's a how-to build plugins with Volcano, but I haven't wrote the docs yet. You could checkout the branch called admin, and see how I'm building a plugin as it should be built using Volcano._

**Comment by persianphilosopher** [comment]
Thank you greatly for your prompt, detailed, and encouraging response. I will gladly explore your suggested path.

Let me also clarify that I have no interest in a blog but I see why my question might suggest otherwise.  I was specifically looking for a flat CMS with markdown support but the content I need to manage would need some minimal structure (folders, in my mind) in order to navigate different set of topics (notes). 

Thank you again!

**Comment by sebastianks** [comment]
You are welcome!

Let me know if you need need anything else. Also - let me know if you build anything for me to see. I would love that!
